@PTFDCallbackServer_HostAddress = https://localhost:44339

POST {{PTFDCallbackServer_HostAddress}}/api/v1/callback
Accept: application/json
Content-Type: application/json

{
  "builderid": "1234",
  "cacheid": "1234",
  "dataid": "1234",
  "documentpath": "C:\\Users\\user\\Documents\\test.pdf",
  "metadata": {
    "title": "Test Document",
    "author": "John Doe",
    "subject": "Test Subject",
    "keywords": "test, document"
  }
}



###
