@PTFDCallbackServer_HostAddress = https://localhost:44339

POST {{PTFDCallbackServer_HostAddress}}/api/v1/callback
Accept: application/json
Content-Type: application/json

{
  "builderid": "1234",
  "documentpath": "C:\\Users\\user\\Documents\\test.pdf",
  "metadata": "<metadata><key>value</key></metadata>"
}



###
